# geo42/Cargo.toml (workspace 根目录)
[workspace]
members = [
    "rtree",
    "geo42"
]
resolver = "2"

[profile.release]
debug = "full"        # 完整调试信息
strip = false
lto = false
opt-level = 1
codegen-units = 1